# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go generate ./cmd/mcli
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      -s -w -X "main.Version={{.Version}}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/mcli
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
